### ISSUE TITLE
t.models is undefined

### ISSUE THREAD

**Issue by flokuek** [mullema/k3-image-clip#10]
I just found an issue in your plugin running on a fresh starterkit with version 3.3.0. The error `t.models is undefined` pops up when clicking on an empty image-clip field.

![Capture2](https://user-images.githubusercontent.com/11317959/68750493-1191aa80-0654-11ea-84a0-3816b8adcae1.PNG)

![Capture](https://user-images.githubusercontent.com/11317959/68749987-44876e80-0653-11ea-8bd1-c2fa1027ab30.PNG)

**To Reproduce**  
1. Go to a page with an image-clip field
2. Click on 'No files selected yet`
3. See error

**Blueprint:**
```
clip:
   layout: list
   type: image-clip
   size: small
   clip:
      minwidth: 400
      minheight: 300
      maxwidth: 800
      maxheight: 600
      ratio: fixed
```

**Kirby Version** 
3.3.0

**Desktop (please complete the following information):**  
 - Browser: Firefox
 - Version: 70
