### ISSUE TITLE
Clip when crop is not explicitly set

### ISSUE THREAD

**Issue by philipmarnef** [mullema/k3-image-clip#11]
When a file is uploaded to an image clip field and the crop is not set through the GUI, the `clip()` method doesn't clip but renders the original image instead. Is there a way to make sure images are always cropped to the ratio set in the blueprint?

**Comment by mullema** [comment]
Hi @philipmarnef 
That's not possible atm. 
I recently ran into the same issue with clients not defining the clip area.

I thought about a new clip option:
```yml
clip:
  defaultwidth: 200
  defaultheight: 400
  defaultposition: top left
```
Where defaultposition works the same way as [Kirby's crop options ](https://getkirby.com/docs/guide/templates/resize-images-on-the-fly#crop-positions)
