### ISSUE TITLE
Image in field does not update after cropping

### ISSUE THREAD

**Issue by lumpysimon** [mullema/k3-image-clip#14]
When I crop an image, the image in the field is not updating to show the new crop. Even after clicking Save it doesn't update - the only way to see the new crop is to refresh the page.

Looking in the Inspector Network tool it looks like the request is returning a zero byte file, even though if I go into the media file I can see the file is there.

<img width="989" alt="Screenshot 2021-02-19 at 12 26 40" src="https://user-images.githubusercontent.com/625372/108504499-e281d400-72ad-11eb-8974-b2653834df54.png">

**Comment by mullema** [comment]
What Kirby and Plugin Version are you using?

**Comment by lumpysimon** [comment]
Kirby 3.5.3
Image Clip: I've installed the plugin as a git submodule, so it's the latest version of the master branch

**Comment by mullema** [comment]
Hm I cannot reproduce this one.
What webserver are you using?
What size are the images?

**Comment by lumpysimon** [comment]
I'm using Valet with PHP 7.4.14 on MacOS. The image is 1500x1000 (but it's the same whatever the image size).

Here's my blueprint:

```
fields:
  text:
    label: text
    type: textarea
    size: small
  pic:
    label: Pic
    type: image-clip
    clip:
      minheight: 400
      minwidth: 400
      ratio: fixed
    layout: cards
```

And here's how I reproduce it:

1. Upload image
2. Click the crop icon
3. Crop and click 'OK'
4. Image in the field does not change.
5. Click Save.
6. Image doesn't change.
7. Reload the page, the field now shows the cropped image.
8. Repeating from step 2 gives the exact same issue.

I've noticed the network inspector is slightly different this time, I'm seeing the NS_BINDING_ABORTED status:

<img width="2027" alt="Screenshot 2021-02-19 at 13 56 34" src="https://user-images.githubusercontent.com/625372/108513389-735eac80-72ba-11eb-8978-160a17dd72e5.png">
