### ISSUE TITLE
Compatibility with Kirby 3.6

### ISSUE THREAD

**Issue by mynameisfreedom** [mullema/k3-image-clip#17]
The field doesn't work with Kirby 3.6.0-alpha.4.

**Comment by mullema** [comment]
The develop branch works with Kirby 3.6.0-beta.2

**Comment by mynameisfreedom** [comment]
You are the man 💪

**Comment by mullema** [comment]
Thank you for the coffee(s) :)

**Comment by ChristophLabacher** [comment]
I and thanks for creating this awesome plugin!

Unfortunately it doesn’t work for me with the released version of Kirby 3.6.

I am using it in my blueprint like this:

```
          teaser_image_square:
            type: image-clip
            label: Teaser Image Square
            multiple: false
            query: page.images
            layout: cards
            clip:
              minwidth: 100
              minheight: 100
              ratio: fixed
```

When I select an image in the Panel it works (and the field is saved to the pages txt file). I then click on the crop button, adjust the position of the cropping and press save. Everything looks fine int the panel, but in this moment the saved information for the field is removed from the pages txt file. When I reload the panel, the field is empty again.
