### ISSUE TITLE
Min and Max set to same value, clip area is not resized on first dialog open

### ISSUE THREAD

**Issue by mullema** [mullema/k3-image-clip#19]
only when clip data is empty.
```
  clip:
    minwidth: 400
    minheight: 300
    maxwidth: 400
    maxheight: 300
    ratio: fixed
```
