### ISSUE TITLE
`query: page.images` doesn't work

### ISSUE THREAD

**Issue by afbora** [mullema/k3-image-clip#20]
> Your query must return a set of files

I'm getting above error when I use following setup:

````yaml
cover:
  type: image-clip
  query: page.images
  multiple: false
  layout: cards
  size: huge
````
